### ISSUE TITLE
tempfile.NamedTemporaryFile() causing error on windows

### ISSUE THREAD

**Issue by bakesi** [scanlime/robot-odyssey-rewired#11]
It seems that `tempfile.NamedTemporaryFile()` in sbt86.py line 1347 causing the following error on windows:

```
> python src/engine/bt_game.py build                                                                                                                 
> SBT86: Applying relocations at [0D3B:0001, 0D3B:003B, 0D3B:004E, 0D3B:01A4]                                                                        
> SBT86: Found patch location [0E3B:67C5, 0E3B:7B8D, 0E3B:8BD8, 0E3B:A4F9, 0E3B:B803] in game.exe for: 'e8____a0ac05a2____a0____a2____e8____a0____a2_
> ___:e9____'                                                                                                                                        
> SBT86: Found jump from 0E3B:67C5 -> 0E3B:66DF                                                                                                      
> ndisasm: unable to open `C:\Users\LENOVO~1\AppData\Local\Temp\tmpfdr05_k7': Permission denied                                                      
> Traceback (most recent call last):                                                                                                                 
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\sbt86.py", line 1391, in iFetch                                     
>     inst = self._iCache[addr.linear]                                                                                                               
> KeyError: 84853                                                                                                                                    
>                                                                                                                                                    
> During handling of the above exception, another exception occurred:                                                                                
>                                                                                                                                                    
> Traceback (most recent call last):                                                                                                                 
>   File "src/engine/bt_game.py", line 15, in <module>                                                                                               
>     bt_common.patch(b)                                                                                                                             
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\bt_common.py", line 31, in patch                                    
>     'g.proc->continueFrom(r, &sub_%X, true);' % loopEntry.linear)                                                                                  
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\sbt86.py", line 1802, in patchAndHook                               
>     self.patch(addr, asmCode, length, deadCode)                                                                                                    
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\sbt86.py", line 1784, in patch                                      
>     self.markDeadCode(i.addr)                                                                                                                      
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\sbt86.py", line 1891, in markDeadCode                               
>     Subroutine(self.image, addr).analyze(self._dynBranches)                                                                                        
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\sbt86.py", line 1451, in analyze                                    
>     i = self.image.iFetch(ptr)                                                                                                                     
>   File "C:\Users\Lenovo_i5\Documents\projects\robot-odyssey-rewired\src\engine\sbt86.py", line 1393, in iFetch                                     
>     raise InternalError("Failed to disassemble instruction at %s" % addr)                                                                          
> sbt86.InternalError: Failed to disassemble instruction at 0E3B:67C5                                                                                
> make: *** [build/bt_game.cpp] Error 1                                                                                                              
```

Environment:
OS: Windows 10 64bit
Python 3.6.6
GNU Make 3.81

**Comment by scanlime** [comment]
Thanks for the detailed report and the fix! Just merged it.
